var $jscomp={scope:{},checkStringArgs:function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";for(var e=b.length,f=a.length,h=Math.max(0,Math.min(c|0,b.length)),g=0;g<f&&h<e;)if(b[h++]!=a[g++])return!1;return g>=f}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===c&&(c=b.length);for(var e=Math.max(0,Math.min(c|0,b.length)),f=a.length;0<f&&0<e;)if(b[--e]!=a[--f])return!1;return 0>=f}},"es6-impl","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6-impl","es3");
(function(){window.asc||(window.asc=function(a){return a.charCodeAt(0)});window.chr||(window.chr=function(a){return String.fromCharCode(a)});window.strpos||(window.strpos=function(a,b,c){a=(a+"").indexOf(b,c||0);return-1===a?!1:a});window.ucwords||(window.ucwords=function(a){return(a+"").replace(/^([a-z\u00E0-\u00FC])|\s+([a-z\u00E0-\u00FC])/g,function(a){return a.toUpperCase()})})})();
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c,d,e,f,h,g,k=0;for(a=Base64._utf8_encode(a);k<a.length;)c=a.charCodeAt(k++),d=a.charCodeAt(k++),e=a.charCodeAt(k++),f=c>>2,c=(c&3)<<4|d>>4,h=(d&15)<<2|e>>6,g=e&63,isNaN(d)?h=g=64:isNaN(e)&&(g=64),b=b+this._keyStr.charAt(f)+this._keyStr.charAt(c)+this._keyStr.charAt(h)+this._keyStr.charAt(g);return b},decode:function(a){var b="",c,d,e,f,h,g=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<
a.length;)c=this._keyStr.indexOf(a.charAt(g++)),d=this._keyStr.indexOf(a.charAt(g++)),f=this._keyStr.indexOf(a.charAt(g++)),h=this._keyStr.indexOf(a.charAt(g++)),c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|h,b+=String.fromCharCode(c),64!==f&&(b+=String.fromCharCode(d)),64!==h&&(b+=String.fromCharCode(e));return b=Base64._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>
6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,d,e,f;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(e=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|e&63),c+=2):(e=a.charCodeAt(c+1),f=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63),c+=3);return b}};
(function(){String.prototype.rotate||Object.defineProperty(String.prototype,"rotate",{value:function(){return this.rotate5().rotate13()}});String.prototype.rotate5||Object.defineProperty(String.prototype,"rotate5",{value:function(){for(var a=[],b,c=this.length,d="0".charCodeAt(),e=d+10;c--;)b=this.charCodeAt(c),a[c]=b>=d&&b<e?String.fromCharCode((b-d+5)%10+d):this.charAt(c);return a.join("")}});String.prototype.rotate13||Object.defineProperty(String.prototype,"rotate13",{value:function(){for(var a=
[],b,c=this.length,d="a".charCodeAt(),e=d+26,f="A".charCodeAt(),h=f+26;c--;)b=this.charCodeAt(c),a[c]=b>=d&&b<e?String.fromCharCode((b-d+13)%26+d):b>=f&&b<h?String.fromCharCode((b-f+13)%26+f):this.charAt(c);return a.join("")}});window.rot13Selection=function(){var a=window.getSelection().toString();window.getSelection().getRangeAt(0).deleteContents();for(var b,c="",d=0;d<a.length;d++)b=a.charCodeAt(d),c=97<=b&&109>=b||65<=b&&77>=b?c+String.fromCharCode(b+13):110<=b&&122>=b||78<=b&&90>=b?c+String.fromCharCode(b-
13):c+String.fromCharCode(b);window.getSelection().getRangeAt(0).insertNode(document.createTextNode(c))}})();
(function(){window.String.prototype.format||Object.defineProperty(String.prototype,"format",{value:function(){var a=this.toString();if(!arguments.length)return a;var b,c="string"===typeof arguments[0]?arguments:arguments[0];for(b in c)c.hasOwnProperty(b)&&(a=a.replace(new RegExp("\\{"+b+"\\}","gi"),c[b]));return a}});window.String.prototype.truncate||Object.defineProperty(String.prototype,"truncate",{value:function(a,b){var c=this.toString();a&&c.length>a&&(c=c.substr(0,a)+b);return c}});window.String.prototype.repeat||
Object.defineProperty(String.prototype,"repeat",{value:function(a){if(1>a)return"";for(var b="",c=this.valueOf();0<a;)a&1&&(b+=c),a>>=1,c+=c;return b}});window.String.prototype.breakup||Object.defineProperty(String.prototype,"breakup",{value:function(a,b){for(var c="",d=0;d<this.length;d+=a)c+=this.substr(d,a),d+a<this.length&&(c+=b);return c}});window.String.prototype.reverse||Object.defineProperty(String.prototype,"reverse",{value:function(){for(var a="",b=this.length;0<b;--b)a+=this.charAt(b-1);
return a}});window.String.prototype.padLeft||Object.defineProperty(String.prototype,"padLeft",{value:function(a,b,c){a=String(""+a);for(null===c&&(c=" ");a.length<b;)a=c+a;return a}});window.String.prototype.escape||Object.defineProperty(String.prototype,"escape",{value:function(){return this.replace(/('|\\)/g,"\\$1")}});window.String.prototype.trim||Object.defineProperty(String.prototype,"trim",{value:function(){return this.replace(/^\s+|\s+$/gm,"")}});window.String.prototype.ltrim||Object.defineProperty(String.prototype,
"ltrim",{value:function(){return this.replace(/^\s+/,"")}});window.String.prototype.rtrim||Object.defineProperty(String.prototype,"rtrim",{value:function(){return this.replace(/\s+$/,"")}});window.String.prototype.left||Object.defineProperty(String.prototype,"left",{value:function(a){return isNaN(a)?this:a>this.length?this:this.substring(0,a)}});window.String.prototype.right||Object.defineProperty(String.prototype,"right",{value:function(a){return isNaN(a)?this:a>this.length?this:this.substring(this.length-
a)}});window.String.prototype.pos||Object.defineProperty(String.prototype,"pos",{value:function(a,b){var c=this.indexOf(a,b||0);return-1===c?!1:c}});window.String.prototype.isNullOrEmpty||Object.defineProperty(String.prototype,"isNullOrEmpty",{value:function(){return null===this||""===this.trim()}});window.String.prototype.toHex||Object.defineProperty(String.prototype,"toHex",{value:function(){var a="",b;for(b=0;b<this.length;b++)a+=""+this.charCodeAt(b).toString(16);return a}});window.String.prototype.strAfterLast||
Object.defineProperty(String.prototype,"strAfterLast",{value:function(a){var b=this.lastIndexOf(a);return 0<=b?this.slice(b+a.length):this}});window.String.prototype.strBeforeLast||Object.defineProperty(String.prototype,"strBeforeLast",{value:function(a){a=this.lastIndexOf(a);return 0<=a?this.slice(0,a):this}});String.prototype.startsWith||Object.defineProperty(String.prototype,"startsWith",{value:function(a,b){return this.substr(b||0,a.length)===a}});String.prototype.endsWith||Object.defineProperty(String.prototype,
"endsWith",{value:function(a,b){var c=this.toString();if("number"!==typeof b||!isFinite(b)||Math.floor(b)!==b||b>c.length)b=c.length;b-=a.length;c=c.indexOf(a,b);return-1!==c&&c===b}});String.prototype.includes||Object.defineProperty(String.prototype,"includes",{value:function(a,b){"number"!==typeof b&&(b=0);return b+a.length>this.length?!1:-1!==this.indexOf(a,b)}});String.prototype.stripTrailingSlash||Object.defineProperty(String.prototype,"stripTrailingSlash",{value:function(){return this.replace(/\/+$/,
"")}});String.prototype.addTrailingSlash||Object.defineProperty(String.prototype,"addTrailingSlash",{value:function(){return this.replace(/[^\/]$/,"/")}})})();
